# Generated by Django 3.2.12 on 2022-04-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respiration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='data_source',
            field=models.CharField(choices=[('original', 'Original Blackrock Spreadsheet'), ('mock', 'Mock data to fill in gaps')], max_length=10),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='station',
            field=models.CharField(max_length=50, unique_for_date='date'),
        ),
    ]
