# Generated by Django 3.2.23 on 2024-01-12 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('respiration', '0002_auto_20220408_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
