language: python
dist: bionic
python:
  - "3.6"
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - make jstest
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
addons:
  apt:
    packages:
      - enchant
      - libgdal-dev
      - libsqlite3-mod-spatialite
