# Generated by Django 3.2.12 on 2022-04-08 12:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mammals', '0002_auto_20170329_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_this_age', to='mammals.animalage', verbose_name='Age of this animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, help_text='age / sex / other notes'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scale_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_this_scale_used', to='mammals.animalscaleused', verbose_name='Scale used to weigh this animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_this_sex', to='mammals.animalsex', verbose_name='Sex of this animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tag_number',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bait',
            name='bait_name',
            field=models.CharField(blank=True, help_text='Label for the type of bait', max_length=256),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='grid_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Grid Square+', to='mammals.gridsquare', verbose_name='Grid Square used for this expedition'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='notes_about_this_expedition',
            field=models.TextField(blank=True, help_text='Notes about this expedition'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='number_of_students',
            field=models.IntegerField(default=0, help_text='How many students participated'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='overnight_temperature_int',
            field=models.IntegerField(default=0, help_text='Overnight Temperature'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='real',
            field=models.BooleanField(default=True, help_text='Is this expedition real or just a test?'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='school_contact_1_email',
            field=models.CharField(blank=True, help_text='First contact @ the school -- phone', max_length=256),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='school_contact_1_name',
            field=models.CharField(blank=True, help_text='First contact @ the school -- name', max_length=256),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='school_contact_1_phone',
            field=models.CharField(blank=True, help_text='First contact @ the school -- e-mail', max_length=256),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='label',
            field=models.CharField(blank=True, help_text='The name of the grade level', max_length=256),
        ),
        migrations.AlterField(
            model_name='gridsquare',
            name='NE_corner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_to_my_SW', to='mammals.gridpoint', verbose_name='Northeast corner'),
        ),
        migrations.AlterField(
            model_name='gridsquare',
            name='NW_corner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_to_my_SE', to='mammals.gridpoint', verbose_name='Northwest corner'),
        ),
        migrations.AlterField(
            model_name='gridsquare',
            name='SE_corner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_to_my_NW', to='mammals.gridpoint', verbose_name='Southeast corner'),
        ),
        migrations.AlterField(
            model_name='gridsquare',
            name='SW_corner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_to_my_NE', to='mammals.gridpoint', verbose_name='Southwest corner'),
        ),
        migrations.AlterField(
            model_name='gridsquare',
            name='access_difficulty',
            field=models.IntegerField(default=0, help_text='is the overall difficulty and length of time for a group\n        of students to get to the square from the Science Center.', verbose_name='Access Difficulty'),
        ),
        migrations.AlterField(
            model_name='gridsquare',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_i_am_in', to='mammals.gridpoint', verbose_name='Center point'),
        ),
        migrations.AlterField(
            model_name='gridsquare',
            name='terrain_difficulty',
            field=models.IntegerField(default=0, help_text='How rough the terrain is on this square.', verbose_name='Terrain Difficulty'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='blurb',
            field=models.TextField(blank=True, help_text='Notes about this habitat (for a habitat page).'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='color_for_map',
            field=models.CharField(blank=True, help_text='RGB color to use on the map', max_length=3),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='image_path_for_legend',
            field=models.CharField(blank=True, help_text='Path to the round colored circle for this habitat', max_length=256),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='label',
            field=models.CharField(blank=True, help_text='Short label for this habitat.', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Name of school', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_1_email',
            field=models.CharField(blank=True, help_text='First contact @ the school   -- phone', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_1_name',
            field=models.CharField(blank=True, help_text='First contact @ the school -- name', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_1_phone',
            field=models.CharField(blank=True, help_text='First contact @ the school -- e-mail', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_2_email',
            field=models.CharField(blank=True, help_text='Second contact @ the school  -- phone', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_2_name',
            field=models.CharField(blank=True, help_text='First contact @ the school -- name', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_2_phone',
            field=models.CharField(blank=True, help_text='Second contact @ the school  -- e-mail', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name of school', max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='notes',
            field=models.CharField(blank=True, help_text='Any other notes about this school.', max_length=256),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Where the animal was seen', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='habitat',
            field=models.ForeignKey(blank=True, help_text='What habitat best describes this location?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mammals.habitat'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='how_many_observed',
            field=models.IntegerField(blank=True, default=None, help_text='How many animals were observed, if applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Where the animal was seen', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='Notes about the location', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='observation_type',
            field=models.ForeignKey(blank=True, help_text='e.g. sighting, camera-trapped, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mammals.observationtype'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='observers',
            field=models.TextField(blank=True, default=None, help_text='Initials of the people who made the observation.', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Best guess at species.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mammals.species'),
        ),
        migrations.AlterField(
            model_name='species',
            name='about_this_species',
            field=models.TextField(blank=True, help_text='A blurb with info about this species at Blackrock'),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(blank=True, help_text='Common name', max_length=512),
        ),
        migrations.AlterField(
            model_name='species',
            name='latin_name',
            field=models.CharField(blank=True, help_text='Binomial species name', max_length=256),
        ),
        migrations.AlterField(
            model_name='trap',
            name='notes',
            field=models.CharField(blank=True, help_text='Notes about this trap.', max_length=256),
        ),
        migrations.AlterField(
            model_name='trap',
            name='trap_string',
            field=models.CharField(blank=True, help_text='This should be a unique string to identify each trap.', max_length=256),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='animal',
            field=models.ForeignKey(blank=True, help_text='Any animals caught', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mammals.animal'),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='bait',
            field=models.ForeignKey(blank=True, help_text='Any bait used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mammals.bait'),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='bait_still_there',
            field=models.BooleanField(default=False, help_text='Was the bait you left in the trap still there\n        when you came back?'),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='habitat',
            field=models.ForeignKey(blank=True, help_text='What habitat best describes this location?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mammals.habitat'),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='notes_about_location',
            field=models.TextField(blank=True, help_text='Notes about the location'),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='notes_about_outcome',
            field=models.TextField(blank=True, help_text='Any miscellaneous notes about the outcome'),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='order',
            field=models.IntegerField(blank=True, help_text='Order in which to show this trap.', null=True),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='student_names',
            field=models.TextField(blank=True, help_text='Names of the students responsible for this location\n        (this would be filled in, if at all, by the instructor after the\n        students have left the forest.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='team_letter',
            field=models.CharField(blank=True, help_text='Name of team responsible for this location.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='team_number',
            field=models.IntegerField(blank=True, help_text='Differentiates the traps each team is in charge of.', null=True),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='transect_bearing',
            field=models.FloatField(blank=True, help_text='Heading of this bearing', null=True),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='transect_distance',
            field=models.FloatField(blank=True, help_text='Distance along this bearing', null=True),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='trap_type',
            field=models.ForeignKey(blank=True, help_text='Which type of trap, if any, was left at this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mammals.traptype'),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='understory',
            field=models.TextField(blank=True, default='', help_text='Understory', null=True),
        ),
        migrations.AlterField(
            model_name='traplocation',
            name='whether_a_trap_was_set_here',
            field=models.BooleanField(default=False, help_text="We typically won't use all the locations suggested by the\n        randomization recipe; this denotes that a trap was actually placed at\n        or near this point."),
        ),
    ]
