# Generated by Django 3.2.16 on 2022-10-25 17:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mammals', '0003_auto_20220408_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridpoint',
            name='geo_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='traplocation',
            name='actual_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='traplocation',
            name='suggested_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
