# Generated by Django 3.2.12 on 2022-04-08 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rights_type',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portal/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='foreststory',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='foreststory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portal/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='foreststory',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='learningactivity',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='learningactivity',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='region',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='station',
            name='activation_date',
            field=models.DateField(verbose_name='activation_date'),
        ),
        migrations.AlterField(
            model_name='station',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='station',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='modified_date'),
        ),
    ]
