# Generated by Django 3.2.16 on 2022-10-25 17:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20220408_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
