# Generated by Django 3.2.12 on 2022-04-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paleoecology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollentype',
            name='display_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pollentype',
            name='type',
            field=models.CharField(choices=[('A', 'Tree or shrub'), ('B', 'Herb'), ('F', 'Fern'), ('Q', 'Aquatic (water) plant'), ('S', 'Spore')], max_length=1),
        ),
    ]
