# Generated by Django 3.2.16 on 2022-10-25 17:49

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='NW_corner',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(), srid=4326),
        ),
        migrations.AddField(
            model_name='tree',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(), srid=4326),
        ),
    ]
